name: Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: fantomas
        run: |
          dotnet tool restore
          dotnet fantomas --check src/

      - run: dotnet build --configuration Release --warnaserror

      # TODO: Remove
      - name: dotnet pack
        run: |
          ls -lA
          mkdir -p ./out/Release && cp README.md ./out/Release
          dotnet pack --configuration Release --warnaserror --output ./out/Release
