name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.202"

      - run: |
          dotnet restore
          dotnet tool restore
        env:
          DOTNET_NOLOGO: true

      - run: dotnet fantomas -- --check --recurse src/
      - run: dotnet build --configuration Release --no-restore -warnaserror
      - run: dotnet test --no-build
