name: Publish to nuget

on:
  release:
    types: [created, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Enable GitHub OIDC token issuance for this job.

    steps:
      - uses: actions/checkout@v6

      - name: dotnet pack
        run: |
          mkdir -p out/Release && cp README.md out/Release/
          dotnet pack --configuration Release --warnaserror --output out/Release -p:PackageVersion=${GITHUB_REF/refs\/tags\/v/''}

      - uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: dotnet nuget push
        run: dotnet nuget push out/Release/*.nupkg --skip-duplicate --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
